version: "2"

services:
  math-api-mongodb:
    image: "mongo:3.7-jessie"
    ports :
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=go_math_api
      - MONGO_INITDB_ROOT_PASSWORD=go_math_api
    command: --auth